export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const SET_APPOINTMENT = 'SET_APPOINTMENT';
export const CLEAR_APPOINTMENT = 'CLEAR_APPOINTMENT';
export const VIEW_APPOINTMENT = 'VIEW_APPOINTMENT';
export const HIDE_APPOINTMENT = 'HIDE_APPOINTMENT';
